[#3] 정류소 검색 화면 초기 구현
f-lab-edu/busoda pull request #5
Opened 2024-12-31 16:40 UTC by parkcheayeon

[정류소 검색 화면 초기 구현 #3](https://github.com/f-lab-edu/busoda/issues/3) 작업하였습니다.

✅ List Item 레이아웃 생성
✅ RecyclerView 추가
✅ StopListAdapter 추가
✅ 더미 데이터를 활용하여 동작 검증
✅ ViewModel을 추가하여 더미 데이터 관리

문서에 맞게 ViewModel은 internal로 선언하였고 
adpapter 또한 :feature:stoplist 모듈 내에서만 사용하기 때문에 internal로 선언하였습니다

2025-01-01 00:07 UTC, Dukoo1 commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListAdapter.kt
> +                textNextStop.text = stopData[2]
List<String>말고 좀 더 stopData를 좀 더 알기쉽게 표현할 방법이 없을까요?
0, 1, 2 처럼 쓰면 가독성도 떨어지고, 실수할 가능성도 있을텐데.
그리고 String외의 타입이 필요해질 수도 있구요

2025-01-01 00:10 UTC, Dukoo1 commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListViewModel.kt
> +    val dummyData = MutableLiveData(
dummy인걸 Fragment에 들키지 않기 위해 실제처럼 이름을 지어보면 어때요?
그럼 추후 dummy데이터를 실제데이터로 바꿔도 Fragment까지 건드릴 일은 줄어들테니...

2025-01-01 00:14 UTC, Dukoo1 commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListViewModel.kt
> +    val dummyData = MutableLiveData(
그리고 이 data를 Fragment에선 읽기만 하고(immutable), 쓰기는 못하게(mutable)하고 싶은데요. 어떻게 하면 될까요?

Fragment에서 쓰기를 할 수 있다는건 Fragment에 비즈니스 로직이 들어갈 수 있다는 뜻이 되어버리거든요. view는 최대한 로직 없이 주어진걸 표현만 하도록 하는게 좋습니다(passive view라고 부름)
추후 unit test를 짤때도 repository, view model까지만 짜고 view(Activity, Fragment, ...)는 짜기가 힘들거든요.

2025-01-01 00:21 UTC, Dukoo1 commented on feature/stoplist/src/main/res/layout/list_item_stop.xml
> +    android:layout_marginEnd="30dp"
크게 중요한건 아닌데요.
이 두 줄을 한 줄로 줄이는 방법도 있어요.
https://developer.android.com/reference/android/view/ViewGroup.MarginLayoutParams 찾아보시면 힌트가 있습니다.

2025-01-01 00:24 UTC, Dukoo1 commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListAdapter.kt
> +internal class StopListAdapter : ListAdapter<List<String>, StopListAdapter.BusStopViewHolder>(BusStopDiffCallback()) {
internal을 하신건 좋은 습관이에요.
public이었다면 app모듈에서도 접근이 가능해지죠.

2025-01-01 00:25 UTC, Dukoo1 commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListFragment.kt
> +        viewModel.removeLastStop()
이건 뭐에요?

2025-01-01 12:34 UTC, parkcheayeon commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListFragment.kt
> +        viewModel.removeLastStop()
Fragment에서 더미 데이터 일부를 제거했을때의 Observe 동작을 검증해보고싶어서 추가해보았습니다
test 용도로는 버튼을 추가해서 구현하는게 더 나을것같아서 수정해보겠습니다!

2025-01-01 13:20 UTC, parkcheayeon commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListAdapter.kt
> +                textNextStop.text = stopData[2]
List<String>대신에 BusStop data class를 만들어서 수정하였습니다

2025-01-01 13:21 UTC, parkcheayeon commented on feature/stoplist/src/main/res/layout/list_item_stop.xml
> +    android:layout_marginEnd="30dp"
감사합니다! 수정했습니다

2025-01-01 13:42 UTC, parkcheayeon commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListViewModel.kt
> +    val dummyData = MutableLiveData(
MutableLiveData는 private로 선언하고, LiveData 타입으로 제공하도록 수정해보았습니다

2025-01-01 14:18 UTC, Dukoo1 commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListViewModel.kt
> +    val busStops: LiveData<List<BusStop>> = dummyData
좋네요. 현업에서도 이렇게 mutable&immutable 짝을 많이 씁니다.

2025-01-02 12:16 UTC, parkcheayeon commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListFragment.kt
> +        viewModel.removeLastStop()
button 추가해서 Observe 동작 테스트 구현하였습니다

2025-01-02 13:24 UTC, Dukoo1 requested changes
리뷰어중에 한명이라도 "Request changes" 선택하면, 머지를 하면 안됩니다. 결사반대라는 뜻이죠 ㅎㅎ

제가 이번 커밋 보고 "Request changes"를 선택한 이유는
1. 데이터 클래스에 뷰 관련 로직이 들어가버렸음.
2. 설사 이 데이터 클래스를 뷰에서만 쓴다고 하더라고, 코드에 다국어문자열을 직접 넣는건 지양하고있음.(안드로이드스튜디오가 경고표시했을거에요.) 다국어를 지원할수있게 바꿔보세요. 좀더 재미있게 한다면, 한글일땐 "XX 방면", 영어일땐 " To XX"로 해보세요. 힌트는 strings.xml 입니다.

2025-01-02 15:09 UTC, Dukoo1 approved these changes

2025-01-02 15:18 UTC, Dukoo1 commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListAdapter.kt
> +                textNextStop.text = formattedNextStopName
좋네요. 이번엔 여기서 한단계 더 나아가볼까요?
BusStop class에는 formatNextStopName()라는 method가 없지만
왼쪽처럼 stopData.formatNextStopName() 처럼 쓸 수 있는 방법이 있습니다.
뭘까요? 힌트는 extension 입니다.

2025-01-02 23:45 UTC, Dukoo1 commented on feature/stoplist/src/main/java/com/chaeny/busoda/stoplist/StopListAdapter.kt
> +        private fun BusStop.formatNextStopName(): String {
좋네요. private 으로 하신 부분도 좋구요.
여기선 이런 함수가 있었으면 쓰기도 좋을텐데... 싶을때 extension이 아주 유용하죠.

2025-01-03 12:45 UTC, merged